name: Build

on:
  workflow_call:
    secrets:
      repo-token:
        required: true

jobs:
  bundle:
    name: Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          #cache: "npm"
          #cache-dependency-path: package-lock.json

      - name: Download core components
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "packages.zip"
          out-file-path: "./"
          extract: true

      - name: Install dependencies
        run: npm i

      - name: Build CSS
        run: npm run build:css

      - name: Build criticals
        run: npm run build:criticals

      - name: Create zip file
        run: bash ./scripts/deployment/create.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./dist/bundle.zip
          retention-days: 1
          if-no-files-found: error