name: Testing

on:
  push:
    branches:
      - main

jobs:
  packages:
    name: Build core packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        run: echo "checkout branch..."

      - name: Install
        run: echo "install..."

      - name: Build
        run: echo "build packages..."

      - name: Create dist packages
        run: echo "build packages..."

      - name: Upload packages artifact
        run: echo "upload build artifact..."

  bundle:
    name: Build ARC bundle
    runs-on: ubuntu-latest
    needs: packages
    steps:
      - name: Checkout branch
        run: echo "checkout branch..."

      - name: Download packages artifact
        run: echo "download packages artifact..."
        
      - name: Install
        run: echo "install..."

      - name: Build CSS
        run: echo "build css..."

      - name: Build criticals
        run: echo "build criticals..."

      - name: Create zip file
        run: echo "create zip file..."

      - name: Upload build artifact
        run: echo "upload build artifact..."

  staging:
    name: Deploy
    needs: bundle
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: staging
      DEPLOY_API_URL: ${{ vars.DEPLOY_API_URL }}
      PROMOTE: true
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  production:
    name: Deploy
    needs: staging
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: production
      DEPLOY_API_URL: ${{ vars.DEPLOY_API_URL }}
      PROMOTE: false
    secrets:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  notify:
    name: Notify deployment
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Checkout branch
        run: echo "checkout branch..."

      - name: Get PR number and commit message
        run: echo "pr number and commite message..."

      - name: Send Teams channel notification
        run: echo "send notification..."