name: Testing

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality.yml

  bundle:
    name: Bundle
    needs: quality
    uses: ./.github/workflows/build.yml
    secrets:
      repo-token: ${{ secrets.GH_TOKEN }}

  staging:
    name: Staging
    needs: bundle
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      promote: false

  production:
    name: Production 
    needs: staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production

  notify:
    name: Notify deployment
    needs: production
    uses: ./.github/workflows/notify.yml
