name: Testing

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality.yml

  bundle:
    name: Bundle
    needs: quality
    uses: ./.github/workflows/build.yml
    secrets:
      repo-token: ${{ secrets.GH_TOKEN }}

  staging:
    name: Staging
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      promote: false

  production:
    name: Production 
    needs: staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production

  notify:
    name: Notify deployment
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get PR number and commit message
        run: echo "pr number and commite message..."

      - name: Send Teams channel notification
        run: echo "send notification..."
