name: Testing

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/quality.yml

  build:
    name: Build
    needs: quality
    uses: ./.github/workflows/build.yml
    secrets:
      repo-token: ${{ secrets.GH_TOKEN }}

  deploy-staging:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      promote: false

  deploy-production:
    name: Deploy 
    needs: deploy-staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      promote: true

  prov:
    name: Prov
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJson(github) }}

  notify:
    name: Notify
    needs: deploy-production
    uses: ./.github/workflows/notify.yml
    with:
      bundle_name: ${{ needs.deploy-production.outputs.bundle_name }}
      deployed_version: ${{ needs.deploy-production.outputs.deployed_version }}
