name: Deploy bundle

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      PROMOTE:
        required: false
        type: boolean
        default: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ vars.DEPLOYMENT_URL }}?d=${{ steps.deploy-service.outputs.deployed_version }}
    outputs:
      deployed_version: ${{ steps.deploy-service.outputs.DEPLOYED_VERSION }}

    env:
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      DEPLOY_API_URL: ${{ vars.DEPLOY_API_URL }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Download build artifact
        run: echo "download build artifact..."

      - name: Upload bundle
        run: |
          chmod +x ${GITHUB_WORKSPACE}/scripts/deployment/upload.sh
          bash ${GITHUB_WORKSPACE}/scripts/deployment/upload.sh

      - name: Terminate oldest service
        run: echo "terminate oldest service..."

      - name: Deploy new service
        id: deploy-service
        run: |
          chmod +x ${GITHUB_WORKSPACE}/scripts/deployment/deploy.sh
          bash ${GITHUB_WORKSPACE}/scripts/deployment/deploy.sh

      - name: Promote service
        if: ${{ inputs.PROMOTE == true }}
        run: echo "promote new service..."