name: Testing

on:
  push:
    branches:
      - main

jobs:
  bundle:
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          repository: jdinicola/playground
          token: ${{ secrets.GH_TOKEN }}
          path: tmp

      - name: Install
        run: cd tmp && npm i

      - name: Build
        run: cd tmp && npm run build

      - name: Create dist packages
        run: find tmp/packages/* -type d -name dist -exec mkdir -p ../packages/{} \; -exec cp -r {}/. ../packages/{} \;

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Build CSS
        run: npm run build:css

      - name: Build criticals
        run: npm run build:criticals

      - name: Create zip file
        run: bash ./scripts/deployment/create.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./dist/bundle.zip
          retention-days: 1
          if-no-files-found: error

  staging:
    name: Deploy
    needs: bundle
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: staging
      PROMOTE: true

  production:
    name: Deploy
    needs: staging
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: production
      PROMOTE: true

  notify:
    name: Notify deployment
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Checkout branch
        run: echo "checkout branch..."

      - name: Get PR number and commit message
        run: echo "pr number and commite message..."

      - name: Send Teams channel notification
        run: echo "send notification..."