name: Notify

on:
  workflow_call:
    inputs:
      bundle_name:
        required: true
        type: string
      deployed_version:
        required: true
        type: string

jobs:
  teams:
    name: Teams
    runs-on: ubuntu-latest

    env:
      BUNDLE_NAME: ${{ inputs.bundle_name }}
      DEPLOYED_VERSION: ${{ inputs.deployed_version }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Prov
        run: |
          echo "${{ inputs.bundle_name }}"

      - name: Get PR number and commit message
        run: |
          echo "PULL_REQUEST_NUMBER=$(echo '${{ github.event.head_commit.message }}' | grep -oP '(?<=#)\d+')" >> $GITHUB_ENV
          echo "COMMIT_MESSSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      - name: Send Teams channel notification
        run: |
          chmod +x ./scripts/deployment/notify.sh
          bash ./scripts/deployment/notify.sh
