name: Notify

on:
  workflow_call:

jobs:
  teams:
    name: Teams notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Get PR number and commit message
        run: echo "pr number and commite message..."

      - name: Send Teams channel notification
        run: echo "send notification..."
