name: Code quality
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main

  workflow_call:

  workflow_dispatch:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Run tests
        run: echo "npm run test"

      - name: Add coverage summary
        run: |
          chmod +x ./scripts/coverage-summary.sh
          bash ./scripts/coverage-summary.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Run ESLint
        run: echo "npm run lint:ci"

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        run: npm i

      - name: Run Prettier
        run: echo "npm run format:check"
